### ISSUE TITLE
Feature request - Allow for transparent PNGs

### ISSUE THREAD

**Issue by ciphertxt** [stephancasas/streamdeck-studio#7]
The current editor only allows for fixed color backgrounds. It would be great to have an option to generate a transparent PNG so that icons play nice with the Stream Deck+ which has a separate background on the touch bar.

**Comment by stephancasas** [comment]
Great idea! I'll roll this into the update along with #6.

**Comment by stephancasas** [comment]
Please review the latest version for custom colour options.

**Comment by EDIflyer** [comment]
Really like the idea of transparent backgrounds - has this been released yet? If so how do we pick them? 😃

**Comment by stephancasas** [comment]
@EDIflyer Yes. Please see [this Reddit post](https://www.reddit.com/r/streamdeckprofiles/comments/zi7lqc/streamdeckstudio_now_supports_custom_and/) for a demo.

**Comment by EDIflyer** [comment]
@stephancasas amazing, thanks - just pulled transparency across to full and worked perfectly, thanks!
