### ISSUE TITLE
Empty zip files when downloading on Mac OS

### ISSUE THREAD

**Issue by CodingWithDavidZ** [stephancasas/streamdeck-studio#8]
Using Mac OS Ventura, files download as zip but the zip files are empty. Double-checked that the files were truly empty by sending the Mac downloaded files to pc and they are indeed empty.

**Comment by stephancasas** [comment]
Are you using Safari?

**Comment by CodingWithDavidZ** [comment]
> 

No, using firefox. I also noticed that the top download icon works fine, just the bottom one where you name the file does not.

**Comment by CodingWithDavidZ** [comment]
I will try in Safari, Chrome, and Brave for you in a second.

**Comment by stephancasas** [comment]
I'm getting a populated ZIP file in FF Dev Edition on Monterrey. Are there icons visible in your collection before you start the ZIP download?

**Comment by CodingWithDavidZ** [comment]
Safari:

- will not show the bottom save icon, or the credits on MBP screen but will on external display
[MBP screen 13"](https://i.imgur.com/itBY3mM.png)
[27" external monitor](https://i.imgur.com/RRSVMN2.png)
Still empty zip files when downloading from bottom download link.

- Chrome
  Same issue with not displaying all content on 13" MBP Screen
  And same issues with downloading (i.e. Top download icon works fine, bottom does not.

- Brave (Chromium)
  As expected, same issues

**Comment by CodingWithDavidZ** [comment]
> Are there icons visible in your collection before you start the ZIP download?

Bingo, user error. 
Can you add a counter to the collections icon? and tool-tips? If you are too busy, I will try to learn how to do that in PHP and issue a pull request when I get time.

**Comment by stephancasas** [comment]
If you'd like to take a crack at it, please feel free to do so! This weekend, I'm going to add the "advanced" colour picker that others have requested, so I should have a chance to get in and get to things then.

You're spot-on on the vertical spacing. My resolution is set to "More Space" on a 5K monitor, so I sometimes forget to account for more practical display sizes.
